

# This file was *autogenerated* from the file aux.sage
from sage.all_cmdline import *   # import sage library

_sage_const_16 = Integer(16); _sage_const_64 = Integer(64); _sage_const_128 = Integer(128); _sage_const_192 = Integer(192)
from sage.all import *

aux_64 = int("ffffffffffffffff",_sage_const_16 )
aux_128 = aux_64 << _sage_const_64 
aux_192 = aux_64 << _sage_const_128 
aux_256 = aux_64 << _sage_const_192 

def print_word(number):
	print(f"{(number&aux_64)}, {(number&aux_128)>>_sage_const_64 }, {(number&aux_192)>>_sage_const_128 }, {(number&aux_256)>>_sage_const_192 }")

