

# This file was *autogenerated* from the file finite_field.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1)
from sqisign_parameters import prime
from sage.all import *

p = prime()

Fp2 = FiniteField(p**_sage_const_2 ,'im_unity',modulus=var('x')**_sage_const_2   + _sage_const_1  , names=('im_unity',)); (im_unity,) = Fp2._first_ngens(1)

