

# This file was *autogenerated* from the file sqisign_parameters.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_16 = Integer(16); _sage_const_75 = Integer(75)
from sage.all import *

reset()

parameters_file = open("../parameters/sqisign_parameters.txt","r")

parameters_raw = parameters_file.read()

parameters_file.close()

parameters_text = parameters_raw.split("\n")

p = int((parameters_text[_sage_const_1 ].split(' '))[_sage_const_2 ],_sage_const_16 )
B = int((parameters_text[_sage_const_2 ].split(' '))[_sage_const_2 ])

mont = int("d72e7d67c30cd3d30a841ab0920655d20afd6c1025a1c2e233625ae400674d4",_sage_const_16 )

f = _sage_const_75 

def prime():
    return p


def B_func():
    return B

def montgomery():
    return mont
